import { Providers } from '../app/store/providers';
import { Open_Sans, Playfair_Display } from "next/font/google";
import "./globals.css";


const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
  display: "swap",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
<html lang="en">
<body className={`${openSans.variable} ${playfair.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}


// import { Provider } from "react-redux";
// import { PersistGate } from "redux-persist/integration/react";
// import { store, persistor } from "./store/index";
// import { Open_Sans, Playfair_Display } from "next/font/google";
// import "./globals.css";

// const openSans = Open_Sans({
//   subsets: ["latin"],
//   variable: "--font-open-sans",
//   display: "swap",
// });

// const playfair = Playfair_Display({
//   subsets: ["latin"],
//   variable: "--font-playfair",
//   display: "swap",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${openSans.variable} ${playfair.variable} antialiased`}>
//         <Provider store={store}>
//           <PersistGate loading={null} persistor={persistor}>
//             {children}{" "}
//           </PersistGate>
//         </Provider>
//       </body>
//     </html>
//   );
// }
